### ISSUE TITLE
Disposal not correct sometimes?

### ISSUE THREAD

**Issue by PauGuillamon** [redwarp/gifdecoder#19]
HI there, found another little bug :) 

I was testing with lots of different gifs and downloaded some from Giphy, I found some stickers are not rendered correctly. For example this one (and others): https://media0.giphy.com/media/kayGhRlOKbJHCqnj9m/giphy.gif ends up in including the first frame when rendering the second:

<img width="304" alt="image" src="https://user-images.githubusercontent.com/37110305/136807187-2c049221-3231-416e-9494-29126746e947.png">

I debugged a bit, this gif has 2 frames with different disposal method, the first frame being RESTORE_TO_BACKGROUND and the second DO_NOT_DISPOSE. Not sure whether that's common or not, but other tools render it correctly.

I have created a branch on my fork so you can quickly test it https://github.com/PauGuillamon/gifdecoder/commits/PGJ/car_gunna_incorrect_disposal I'm not sure what would be the best fix here, since I don't know the specs of GIF.

Let me know if I can help in any way. Thank you!

**Comment by redwarp** [comment]
Fixed by https://github.com/redwarp/gifdecoder/commit/2556af6478e65938864b500891d4d3fb9579a023

**Comment by redwarp** [comment]
Version 0.8.1 released!
