### ISSUE TITLE
GifDrawable#getFrame() detect if any pixel is transparency may slow down the decode procedure for those large resolution frame

### ISSUE THREAD

**Issue by vince-styling** [redwarp/gifdecoder#22]
should we default the ARGB_8888 to wield space for time? especially I give up your BitmapCache, instead used only one bitmap instance through the whole decode procedure, I will explain in another issue

**Comment by redwarp** [comment]
I think you are right, seems like a useless optimization in this day and age

**Comment by redwarp** [comment]
Reopening it, I have not yet updated to only use 8888

**Comment by redwarp** [comment]
I decided to keep the transparency check, but to cache it, so it's only calculated the first time each frame is decoded.

**Comment by redwarp** [comment]
Actually, changed my mind 😂 , I'll simplify to ARGB_8888, this way I can also use a direct `copyPixelsFromBuffer` method, slightly more optimized.

**Comment by vince-styling** [comment]
pay a test about time consuming of copyPixelsFromBuffer vs setPixels, on android-11 there no obvious difference, but setPixels faster over 4 times on android-13(0.515ms vs 2.102ms)

**Comment by redwarp** [comment]
That seems counter intuitive, I'll have to bench that too 🤔

**Comment by vince-styling** [comment]
perhaps I was wrong, because I haven't much devices, my test may less accurate, don't bench before you confirm it

**Comment by redwarp** [comment]
I added a bench to compare both, and copyPixels is always faster. It makes only a really little difference though, as the biggest part of creating a frame is decoding, not copying the result in a bitmap.
